# Generated by Django 5.2.7 on 2025-10-16 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomepython', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20)),
                ('cargaHoraria', models.IntegerField()),
                ('ementa', models.TextField()),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.professor')),
            ],
        ),
    ]
