# Generated by Django 5.2.7 on 2025-10-24 20:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_inscricao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Candidatura',
        ),
        migrations.RenameField(
            model_name='disciplina',
            old_name='nomepython',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='registromonitoria',
            old_name='dataEntrada',
            new_name='dataRegistro',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='disciplina',
        ),
        migrations.RemoveField(
            model_name='inscricao',
            name='disciplina',
        ),
        migrations.RemoveField(
            model_name='registromonitoria',
            name='email',
        ),
        migrations.RemoveField(
            model_name='registromonitoria',
            name='matricula',
        ),
        migrations.RemoveField(
            model_name='registromonitoria',
            name='nome',
        ),
        migrations.AddField(
            model_name='inscricao',
            name='data_candidatura',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='documentos',
            field=models.FileField(blank=True, null=True, upload_to='documentos/'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='status',
            field=models.CharField(default='Pendente', max_length=20),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='vaga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='myapp.vaga'),
        ),
        migrations.AddField(
            model_name='registromonitoria',
            name='aluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registros_monitoria', to='myapp.aluno'),
        ),
        migrations.AddField(
            model_name='registromonitoria',
            name='descricao_atividades',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='registromonitoria',
            name='vaga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registros_monitoria', to='myapp.vaga'),
        ),
        migrations.AddField(
            model_name='registromonitoria',
            name='validado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.professor'),
        ),
        migrations.AddField(
            model_name='vaga',
            name='prazo_inscricao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vaga',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vagas', to='myapp.professor'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='myapp.professor'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='myapp.aluno'),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='disciplina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vagas', to='myapp.disciplina'),
        ),
    ]
