# Generated by Django 5.2.7 on 2025-10-30 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_delete_candidatura_rename_nomepython_disciplina_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='descricao',
            field=models.TextField(default=''),
        ),
    ]
