@startuml
left to right direction
skinparam actorStyle awesome
skinparam usecase {
  BackgroundColor #EAEAEA
  BorderColor #333
}

actor "Aluno" as Aluno
actor "Professor" as Professor
actor "Direção" as Direcao 


rectangle "Sistema de Monitoria" {
package "Autenticação e Perfil" {
    usecase "Login" as UC_Login
  usecase "Esqueci a Senha" as UC_Esqueci
  usecase "Editar Perfil" as UC_EditarPerfil
}
package "Gerenciamento de Candidaturas" {  
  usecase "Cadastro" as UC_Cadastro
  usecase "Candidatar-se a Vaga" as UC_Candidatar
  usecase "Visualizar Candidatura" as UC_Visualizar
  usecase "Cancelar Candidatura" as UC_Cancelar
}
package "Gerenciamento de Vagas" {
  usecase "Criar Vaga" as UC_CriarVaga
  usecase "Editar Vaga" as UC_EditarVaga
  usecase "Gerenciar Candidatos" as UC_Gerenciar
  usecase "Excluir Vaga" as UC_Excluir
}
package "Relatórios e Dashboard" {
  usecase "Gerar Relatórios" as UC_Relatorios
  usecase "Visualizar Dashboard" as UC_Dashboard
}
}
Aluno --> UC_Login
Aluno --> UC_Esqueci
Aluno --> UC_EditarPerfil
Aluno --> UC_Cadastro
Aluno --> UC_Candidatar
Aluno --> UC_Visualizar
Aluno --> UC_Cancelar

Professor --> UC_Login
Professor --> UC_Esqueci
Professor --> UC_EditarPerfil
Professor --> UC_CriarVaga
Professor --> UC_EditarVaga
Professor --> UC_Gerenciar
Professor --> UC_Excluir

UC_Login <-- Direcao
UC_Esqueci <-- Direcao
UC_EditarPerfil <-- Direcao
UC_CriarVaga <-- Direcao
UC_EditarVaga <-- Direcao
UC_Gerenciar <-- Direcao
UC_Excluir <-- Direcao
UC_Dashboard <-- Direcao
UC_Relatorios <-- Direcao
@enduml
